### PR TITLE
Initial implementation with download bundle option

### PR DESCRIPTION
**Pull request by parente**
- Project automation
- README
- LICENSE
- Basic _File &rarr; Download as &rarr; Microservice Docker bundle (.zip)_ implementation

### CODE REVIEW

**Comment by parente** [comment]
@Lull3rskat3r @jtyberg @nitind Feedback greatly appreciated. Tested manually using the included hello_world notebook.

**Comment by jtyberg** [comment]
The implementation looks like a good start.

So the big question, as you point out, is how to replicate the environment?

**Comment by parente** [comment]
> So the big question, as you point out, is how to replicate the environment?

Unless you're in a walled garden (e.g., cloud hosting) where your notebook server, your kernel compute cluster, your docker registry, your package manager, and your data store are all known, the answer is "manually."

**Comment by jtyberg** [comment]
Agreed.  Too much magic otherwise.

**Comment by parente** [comment]
Worse: magic that only works in certain very specific cases like "If you use Python 3 and you start from Docker image foo/bar, then we automatically replicate your pip installs. Otherwise, it doesn't work." Yuck.

This is actually a key constraint that needs to be in the dashboards roadmap too. (/me adds it now ...)

**Comment by parente** [comment]
Merging as first example of using new jupyter_cms bundlers feature.

**Pull request merged**
